import type { Metadata } from "next";
import "./globals.css";
import { QueryClientProvider } from '@tanstack/react-query';
import { queryClient } from "@/utils/reactQuery";

export const metadata: Metadata = {
  title: "React Query Sample",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <div className="min-h-screen bg-gray-50">
            <header className="bg-white shadow py-4 mb-6">
              <h1 className="text-center text-2xl font-bold">React Query Demo</h1>
            </header>
            <main className="px-4 max-w-2xl mx-auto">{children}</main>
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
